apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.pod_properties.app.paths.auth }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.App_Sub_Chart.app.name }}
                port:
                  number: {{ .Values.App_Sub_Chart.app.port }}
          - path: {{ .Values.ingress.pod_properties.app.paths.reading }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.App_Sub_Chart.app.name }}
                port:
                  number: {{ .Values.App_Sub_Chart.app.port }}
          - path: {{ .Values.ingress.pod_properties.app.paths.reading_type }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.App_Sub_Chart.app.name }}
                port:
                  number: {{ .Values.App_Sub_Chart.app.port }}
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.App_Sub_Chart.app.name }}
                port:
                  number: {{ .Values.App_Sub_Chart.app.port }}
          - path: /v3
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.App_Sub_Chart.app.name }}
                port:
                  number: {{ .Values.App_Sub_Chart.app.port }}
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.App_Sub_Chart.app.name }}
                port:
                  number: {{ .Values.App_Sub_Chart.app.port }}

    - host: myfront
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.Front_Sub_Chart.front.name }}
                port:
                  number: {{ .Values.Front_Sub_Chart.front.port }}

    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chart-prometheus-server
                port:
                  number: 9090
