apiVersion: v2
name: App-Chart
description: My helm chart for k8s
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 15.5.16
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: App-Sub-Chart
    version: 0.1.0
    repository: file://../app-sub-chart