version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: time_tracking_db
    ports:
      - 5433:5432
    restart: on-failure
    environment:
      POSTGRES_USER: tracker_user
      POSTGRES_PASSWORD: tracker_password
      POSTGRES_DB: tracker_db