apiVersion: v2
name: App-Chart
description: My helm chart for k8s
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgres
    version: 1.5.0
    repository: https://romanow.github.io/helm-charts/
  - name: App_Sub_Chart
    version: 0.1.0
    repository: file://../app-sub-chart
  - name: Front_Sub_Chart
    version: 0.1.0
    repository: file://../front-sub-chart
  - name: prometheus
    version: 25.24.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: jaeger
    version: 3.1.1
    repository: https://jaegertracing.github.io/helm-charts
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.10.2
  - name: logstash
    version: 8.5.1
    repository: https://helm.elastic.co