postgres:
  defaultDatabase:
    name: monitoring_service_db
    user: t1_user
    password: password
  ports:
    internal: 5432
  serviceName: chart

App_Sub_Chart:
  app:
    name: myapp
    port: 8085
    replicas: 1
  jaeger:
    host: chart-jaeger-collector
    port: 4317

Front_Sub_Chart:
  front:
    name: myfront
    port: 8080
    replicas: 1

ingress:
  host: monitoring-service
  pod_properties:
    app:
      paths:
          auth: /auth
          reading: /reading
          reading_type: /reading-type
    front:
      paths:
        root: /
prometheus:
  server:
    global:
      scrape_interval: 15s

jaeger:
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

logstash:
  service:
    ports:
    - name: beats
      port: 5000
      protocol: TCP
      targetPort: 5000
  logstashPipeline:
    logstash.conf: |
        input {
          tcp {
            port => 5000
            codec => json
          }
        }
        output { 
          stdout { codec => rubydebug }
        }
    
