postgres:
  defaultDatabase:
    name: monitoring_service_db
    user: t1_user
    password: password
  ports:
    internal: 5432

ingress:
  host: monitoring-service
  pod_properties:
    app:
      service_name: localhost
      port: 8085
      paths:
          auth: /auth
          reading: /reading
          reading_type: /reading-type
    front:
      service_name: myfront
      port: 8080
      paths:
        root: /
