postgres:
  defaultDatabase:
    name: monitoring_service_db
    user: t1_user
    password: password
  ports:
    internal: 5432

App_Sub_Chart:
  app:
    name: myapp
    port: 8085

Front_Sub_Chart:
  front:
    name: myfront
    port: 8080

ingress:
  host: monitoring-service
  pod_properties:
    app:
      paths:
          auth: /auth
          reading: /reading
          reading_type: /reading-type
    front:
      paths:
        root: /
