apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}
spec:
  #type: LoadBalancer
  selector:
    app: {{ .Values.front.name }}
  ports:
    - port: 8080
      targetPort: {{ .Values.front.port }}