spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/metrics_db
    username: metrics_user
    password: metrics_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
app:
  kafka:
    kafkaMessageTopic: message-topic
    kafkaMessageGroupId: message-topic-group-id

server:
  port: 8086