apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
    prometheus.io/path: '/actuator/prometheus'
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 8085
      targetPort: {{ .Values.app.port }}