apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://{{ .Values.postgres.serviceName }}:{{ .Values.postgres.ports.internal }}/{{ .Values.postgres.defaultDatabase.name }}"
            - name: POSTGRES_USER
              value: {{ .Values.postgres.defaultDatabase.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.defaultDatabase.password }}
            - name: JAEGER_COLLECTOR_URL
              value: "http://{{ .Values.jaeger.host }}:{{ .Values.jaeger.port }}"
      restartPolicy: Always