app:
  name: myapp
  image: dimatch86/monitoring-service:1.4-SNAPSHOT
  replicas: 1
  port: 8085

postgres:
  defaultDatabase:
    name: monitoring_service_db
    user: t1_user
    password: password
  ports:
    internal: 5432