app:
  name: myapp
  image:
    repository: dimatch86/monitoring-service
    tag: 1.9-SNAPSHOT
  replicas: 1
  port: 8085

postgres:
  defaultDatabase:
    name: monitoring_service_db
    user: t1_user
    password: password
  ports:
    internal: 5432
  serviceName: chart
jaeger:
  host: chart-jaeger-collector
  port: 4317
logstash:
  url: "chart-logstash:5000"