apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.org/proxy-connect-timeout: "30s"
    #nginx.org/proxy-read-timeout: "20s"
    #nginx.org/client-max-body-size: "4m"
    #nginx.org/proxy-hide-headers: localhost:8080
    #nginx.org/proxy-pass-headers: localhost:8080
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.app.paths.auth }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.app.service_name }}
                port:
                  number: {{ .Values.ingress.app.port }}
          - path: {{ .Values.ingress.app.paths.reading }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.app.service_name }}
                port:
                  number: {{ .Values.ingress.app.port }}
          - path: {{ .Values.ingress.app.paths.reading_type }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.app.service_name }}
                port:
                  number: {{ .Values.ingress.app.port }}
          - path: {{ .Values.ingress.front.paths.root }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.front.service_name }}
                port:
                  number: {{ .Values.ingress.front.port }}