apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}