version: '3'
services:
  postgres2:
    image: postgres:12.3
    container_name: postgres2
    ports:
      - 5434:5432
    restart: on-failure
    environment:
      POSTGRES_USER: ylab_user
      POSTGRES_PASSWORD: ylab_password
      POSTGRES_DB: monitoring_service_db
  frontend:
    container_name: frontend
    image: dimatch86/monitoring-service-frontend
    ports:
      - "8081:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # the jaeger UI
      - "4317:4317" # the OpenTelemetry collector grpc
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  app:
    image: dimatch86/monitoring-service:ad1196cc2ffaeb96904fd5edb9c6ba8260b7db91560f8e46cf10a76534db61f6
    container_name: app
    ports:
      - 8085:8085
    environment:
      DATABASE_URL: jdbc:postgresql://postgres2:5432/monitoring_service_db
      POSTGRES_USER: ylab_user
      POSTGRES_PASSWORD: ylab_password
    restart: on-failure